// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireapp

import (
	"github.com/khanakia/mangobp/mango/cache_nats"
	"github.com/khanakia/mangobp/mango/cacherdbms"
	"github.com/khanakia/mangobp/mango/cli"
	"github.com/khanakia/mangobp/mango/configmgr"
	"github.com/khanakia/mangobp/mango/dbconn"
	"github.com/khanakia/mangobp/mango/geo"
	"github.com/khanakia/mangobp/mango/gormdb"
	"github.com/khanakia/mangobp/mango/logdb"
	"github.com/khanakia/mangobp/mango/natso"
	"github.com/khanakia/mangobp/mango/xmail/xmail_app"
	"github.com/khanakia/mangobp/pkg/auth/auth_app"
	"github.com/khanakia/mangobp/pkg/cache_natsapi"
	"github.com/khanakia/mangobp/pkg/dapp"
	"github.com/ubgo/gofm/logger"
	"gorm.io/gorm"
)

// Injectors from wireapp.go:

func Init() Plugin {
	config := NewConfigMgrConfig()
	configMgr := configmgr.New(config)
	cliCli := cli.New()
	loggerLogger := logger.New()
	dbconnConfig := dbconn.Config{
		ConfigMgr: configMgr,
	}
	dbConn := dbconn.New(dbconnConfig)
	gormdbConfig := NewGormConfig(dbConn)
	gormDB := gormdb.New(gormdbConfig)
	natsoConfig := natso.Config{
		Cli: cliCli,
	}
	natsoNatso := natso.New(natsoConfig)
	db := NewGormDb(gormDB)
	cacherdbmsConfig := cacherdbms.Config{
		DB: db,
	}
	rdbms := cacherdbms.New(cacherdbmsConfig)
	cache_natsConfig := cache_nats.Config{
		Natso: natsoNatso,
	}
	cacheNats := cache_nats.New(cache_natsConfig)
	logdbConfig := logdb.Config{
		Cli:    cliCli,
		GormDB: gormDB,
		Natso:  natsoNatso,
	}
	logDb := logdb.New(logdbConfig)
	xmail_appConfig := xmail_app.Config{
		Cli:    cliCli,
		GormDB: gormDB,
		Natso:  natsoNatso,
	}
	xmail := xmail_app.New(xmail_appConfig)
	auth_appConfig := auth_app.Config{
		Cli:    cliCli,
		GormDB: gormDB,
		Natso:  natsoNatso,
		Cache:  cacheNats,
	}
	auth := auth_app.New(auth_appConfig)
	geoConfig := geo.Config{
		Cli:    cliCli,
		GormDB: gormDB,
	}
	geoGeo := geo.New(geoConfig)
	dappConfig := dapp.Config{
		Cli:    cliCli,
		GormDB: gormDB,
		Natso:  natsoNatso,
		Cache:  cacheNats,
	}
	dappDapp := dapp.New(dappConfig)
	cache_natsapiConfig := cache_natsapi.Config{
		Natso: natsoNatso,
		Cache: cacheNats,
	}
	cacheNatsApi := cache_natsapi.New(cache_natsapiConfig)
	plugin := Plugin{
		ConfigMgr:    configMgr,
		Cli:          cliCli,
		Logger:       loggerLogger,
		DbConn:       dbConn,
		GormDB:       gormDB,
		Natso:        natsoNatso,
		CacheRdbms:   rdbms,
		Cache:        cacheNats,
		LogDb:        logDb,
		Xmail:        xmail,
		Auth:         auth,
		Geo:          geoGeo,
		Dapp:         dappDapp,
		CacheNats:    cacheNats,
		CacheNatsApi: cacheNatsApi,
	}
	return plugin
}

// wireapp.go:

func NewGormConfig(dbConn *dbconn.DbConn) gormdb.Config {
	return gormdb.Config{
		DB: dbConn.SqlDb,
	}
}

func NewConfigMgrConfig() configmgr.Config {
	return configmgr.Config{}
}

func NewGormDb(gormdb2 gormdb.GormDB) *gorm.DB {
	return gormdb2.DB
}
